spring:
  datasource:
    username: slx
    password: slx_9920
    url: jdbc:mysql://rm-j6c2k7uyo6n6o2870no.mysql.rds.aliyuncs.com/chatgpt?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 150MB     # 设置单个文件大小
      max-request-size: 150MB  # 设置单次请求文件的总大小

  rabbitmq:
    host: 124.71.110.30
    username: admin
    password: admin
    virtual-host: /chatgpt
    listener:
      simple:
        prefetch: 1    #（设置preFetch这个值，可以控制预取消息的上限）每次只能获取一条消息，处理完成才能获取下一个消息

mybatis-plus:
  mapper-locations: classpath:mappering/*.xml

minio:
  endpoint: http://124.71.110.30:9000
  accessKey: minio
  secretKey: minio123
  bucket: file