spring:
  datasource:
    username:
    password:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 150MB     # 设置单个文件大小
      max-request-size: 150MB  # 设置单次请求文件的总大小

  rabbitmq:
    host:
    username:
    password:
    virtual-host:
    listener:
      simple:
        prefetch: 1    #（设置preFetch这个值，可以控制预取消息的上限）每次只能获取一条消息，处理完成才能获取下一个消息

  redis:
    host: 8.137.71.187
    port: 6379                # Redis的端口
    password: redis         # Redis服务器连接密码

mybatis-plus:
  mapper-locations: classpath:mappering/*.xml

minio:
  endpoint:
  accessKey:
  secretKey:
  bucket: